// <auto-generated />
using CocktailClient.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CocktailClient.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230509204054_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CocktailClient.Shared.Alcool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alcools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Avec Alcool"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sans Alcool"
                        });
                });

            modelBuilder.Entity("CocktailClient.Shared.SuperRecette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlcoolId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ingredient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlcoolId");

                    b.ToTable("SuperRecettes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlcoolId = 1,
                            Description = "boisson forte",
                            Ingredient = "Rhum",
                            Name = "ABC"
                        },
                        new
                        {
                            Id = 2,
                            AlcoolId = 2,
                            Description = "à consommer à tout heure",
                            Ingredient = "eau, sirop",
                            Name = "Grenadine"
                        });
                });

            modelBuilder.Entity("CocktailClient.Shared.SuperRecette", b =>
                {
                    b.HasOne("CocktailClient.Shared.Alcool", "Alcool")
                        .WithMany()
                        .HasForeignKey("AlcoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alcool");
                });
#pragma warning restore 612, 618
        }
    }
}
