version: '3.9'

services:
  database: 
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-Ribeiro}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vampires}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-ribeirochristophe63@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-vampires}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres

    restart: unless-stopped
networks:
  postgres:
volumes:
  postgres:
  pgadmin:  